### ISSUE TITLE
Neo4j Tracer support

### ISSUE THREAD

**Issue by bboure** [lumigo-io/lumigo-node#187]
Hi, is there any plan for supporting automatic tracing for [neo4j](https://github.com/neo4j/neo4j-javascript-driver) ? 

I'd be happy to help and work on a PR if that is something you consider and I can help.

**Comment by efimk-lu** [comment]
Hey @bboure , I love your suggestion, I'll be more than happy to hear about the use case, and how you are using Lumigo. Let's have a short zoom meeting next week?  How can I contact you via email?

**Comment by bboure** [comment]
@efimk-lu  thanks for getting back to me. Please DM me on twitter https://twitter.com/Benoit_Boure

**Comment by efimk-lu** [comment]
@bboure for some reason I can't find the DM button on your profile, can you try me https://twitter.com/TServerless ?
