### ISSUE TITLE
Please Add Support for NodeJS 16

### ISSUE THREAD

**Issue by suds-sky** [lumigo-io/lumigo-node#382]
**Describe the solution you'd like**

Support nodejs v16 based lambdas

**Additional context**

As AWS lambda now started to support Nodejs 16 runtime, we have migrated our lambdas to Nodejs 16 but we can't get the lumigo setup for those lambdas. Needed to setup lumigo for prod account.

**Comment by doriaviram** [comment]
Hey @suds-sky Its actually in our sprint, we will keep you posted

**Comment by suds-sky** [comment]
> Hey @suds-sky Its actually in our sprint, we will keep you posted

Nice! Thank you. Looking forward to it 😄

**Comment by doriaviram** [comment]
Hey @suds-sky we released node 16 support on `v1.71.5`
Thanks
