### ISSUE TITLE
Tracer should handle traceIdArr greater than 3 and should not be throwing unhandled errors

### ISSUE THREAD

**Issue by builtbylane** [lumigo-io/lumigo-node#431]
https://github.com/lumigo-io/lumigo-node/blob/c4e3228043030170956f899f5ce28c924b183999/src/utils.ts#L79

```typescript;
export const getTraceId = (awsXAmznTraceId) => {
  if (!awsXAmznTraceId) {
    throw new Error('Missing _X_AMZN_TRACE_ID in Lambda Env Vars.');
  }

  const traceIdArr = awsXAmznTraceId.split(';');
  if (traceIdArr.length !== 3) {
    throw new Error('Expected 3 semi-colon separated parts in _X_AMZN_TRACE_ID.');
  }

  const traceId = {};
  // XXX Populates Root, Parent and Sampled keys.
  traceIdArr.forEach((item) => {
    const [key, value] = item.split('=');
    traceId[key] = value;
  });

  if (!traceId['Root'] || !traceId['Parent'] || !traceId['Sampled']) {
    throw new Error(`Either Root, Parent or Sampled weren't found in traceId.`);
  }

  // @ts-ignore
  const transactionId = traceId.Root.split('-')[2];

  // @ts-ignore
  traceId.transactionId = transactionId;

  return traceId;
};
```

Can this be written without ts-ignores?
what does the // XXX comment mean?
Why check that the traceIdArr is exactly 3, if those values are being checked lower down?

Note: this code will break systems that every pass in a `awsXAmznTraceId` that has extra information attached.

**Comment by builtbylane** [comment]
Without a full refactor, this would make the code safer. 
```
  if (traceIdArr.length >= 3) {
    throw new Error('Expected at least 3 semi-colon separated parts in _X_AMZN_TRACE_ID.');
  }
```

**Comment by doriaviram** [comment]
Hey, @builtbylane Thanks for reporting, we are checking the issue

**Comment by builtbylane** [comment]
this is a redacted but real _X_AMZN_TRACE_ID that breaks lumigo: `Root=1-640f97b4-12345;Parent=1234;Sampled=0;Lineage=1234:0`

as a first step, the code should not strictly be looking for exactly 3 parts. 

As a followup, this code feels unsafe for production systems. There are too many areas where an unexpectedly formed traceId could blow up a lambda. For instance, what if the Root had fewer than 2 hyphens? Is there a reason an error like that should block the execution of a lambda?

**Comment by Nxtra** [comment]
@builtbylane , does this break all currently deployed lambdas that are wrapped with the lumigo tracer?

**Comment by Nxtra** [comment]
FWIW, I have multiple environments live and the once using "aws-sdk": "2.1301.0" are still executing fine.
Where I upgraded to "aws-sdk": "2.1333.0" I encounter the error above.

**Comment by builtbylane** [comment]
This fix will get us back up, however this code on a whole does not feel production-grade: 

1. inconsistent patterns for catching errors make it hard to reason with
2. Unhandled errors that would end up blowing up the entire lambda
3. lots of typescript ignores that could easily lead to runtime issues
4. object mutations should not be allowed. Should consider enforcing strict object immutability to prevent unintended mutations

Ultimately, it's the 2nd issue that concerns me the most. There's too many ways in which unexpected data from AWS would not be handled gracefully and end up blowing up our lambda again.

**Comment by Nxtra** [comment]
@doriaviram , thanks! Patching it now. 

Extra info: 
Rolling back to aws-sdk 2.1301 as I first thought did not resolve it.
Only saw it on my dev account were I had recently deployed new function versions.
No impact on my test and prod account which were entouched.

**Comment by doriaviram** [comment]
@builtbylane Yep, we are going to refactor this part, be sure about that

**Comment by StampixSMO** [comment]
This started breaking all our lambdas all of a sudden that have the tracer enabled ...

**Comment by doriaviram** [comment]
Hey @StampixSMO can you update to:
https://github.com/lumigo-io/lumigo-node/releases/tag/v1.80.1

**Comment by mmanciop** [comment]
Hi, @StampixSMO, we are likely issuing a further hardening, see #433

**Comment by doriaviram** [comment]
The issue was fixed on the PR https://github.com/lumigo-io/lumigo-node/pull/432, and another refactor we did to improve the handling of `_X_AMZN_TRACE_ID` is https://github.com/lumigo-io/lumigo-node/pull/433 that closing this issue.

From version `1.80.1`, the issue was fixed.
Thanks for reporting @builtbylane @StampixSMO @Nxtra
