### ISSUE TITLE
EMFILE: too many files open

### ISSUE THREAD

**Issue by builtbylane** [lumigo-io/lumigo-node#468]
**Describe the bug**

```shell
Runtime.UnhandledPromiseRejection: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_ho
    at /opt/nodejs/node_modules/@lumigo/tracer/dist/tracer/tracer.js:269:31
    at step (/opt/nodejs/node_modules/@lumigo/tracer/dist/tracer/tracer.js:33:23)
    at Object.next (/opt/nodejs/node_modules/@lumigo/tracer/dist/tracer/tracer.js:14:53)
    at /opt/nodejs/node_modules/@lumigo/tracer/dist/tracer/tracer.js:8:71
```

This is not the first time we've seen this issue with Lumigo tracer. It happens very occasionally during extreme bursts of traffic. 

In this case, our lambda does not make any filesystem calls. We suspect it's Lumigo tracer making too many FS calls.

**To Reproduce**

Very difficult to reproduce. Happens under extreme burst

**Runtime details**
AWS_Lambda_nodejs18.x (eu-central-1_

**Screenshots**
![CleanShot 2023-12-07 at 12 26 45](https://github.com/lumigo-io/lumigo-node/assets/149081/74fd282f-80e2-447b-a429-09b9df2df8af)

Last Occurrence
`11:02:10 PM EST`

**Questions**

* Tracer makes http calls and filesystem calls. What happens if for example, Lumigo connection fails and retries? 
* How many files from FS would tracer load for a normal stacktrace / log execution?

**Comment by doriaviram** [comment]
Hey @builtbylane Lumigo should not do any FS calls, we will checkout it out

**Comment by builtbylane** [comment]
@doriaviram we were able to reproduce and eliminate.

We were connecting to a queue in the lambda. We've mitigated issue by caching queue connection between lambda invocations. 

That said, wonder if there's a better way for Lumigo to handle these errors. We did not rule out that Lumigo tracer wasn't contributing to the total "too many files open" tally.
