### ISSUE TITLE
Critical Error at Runtime with the newest Version of lumigo-node

### ISSUE THREAD

**Issue by mrmonat** [lumigo-io/lumigo-node#502]
**Describe the bug**
The following lines https://github.com/lumigo-io/lumigo-node/blob/270e19c433140087b86588474153a711a48a39ae/auto-instrument-handler/index.js#L24-L31 added in #500 lead to a critical error at runtime.

```json
{
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected token 'export'",
    "stack": [
        "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token 'export'",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1084:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

**Expected behavior**
Because `lumigo-autoinstrument-handler/index.js` has to be a "CommonJS" file, the "export" keyword is not allowed there.

**Runtime details**
- node20

**Comment by matthewbpt** [comment]
I can confirm this issue also affects our stack

**Comment by GuyMoses** [comment]
released a fix (reverted) version:
`https://www.npmjs.com/package/@lumigo/tracer/v/1.99.2`

thanks, we will take this internally
